### ISSUE TITLE
bug: SVG randomly stops working in Linux

### ISSUE THREAD

**Issue by marc2332** [marc2332/valin#52]
For whatever reason when I open a folder in freya-editor, all SVGs stop working

**Comment by marc2332** [comment]
![image](https://github.com/marc2332/valin/assets/38158676/e14d9c18-3543-4f03-a540-05a0ea3e9f7d)

**Comment by marc2332** [comment]
I wonder if it could be because of 

https://github.com/marc2332/freya/blob/9d37c3c2532c680b309d35bdb5561bc91be26400/crates/renderer/src/window.rs#L63-L64

**Comment by marc2332** [comment]
Hey @pragmatrix, sorry for pinging you here, do you have any idea what could be causin this? It doesn't happen on Windows.

Maybe https://github.com/marc2332/valin/issues/52#issuecomment-2144031556 ? I haven't tried disabling it yet, will do soon, but I doubt that's the issue..

**Comment by marc2332** [comment]
For reference, this is how it should look: 
![image](https://github.com/marc2332/valin/assets/38158676/7cfedddb-4c27-4523-baaf-99da8784fa00)

**Comment by pragmatrix** [comment]
I've no idea. Initially I though it may be that opening a folder may change the current directory on Linux, but as I've seen in the source, the svgs are loaded at compile time.

**Comment by marc2332** [comment]
Yeah, they are statically linked and, I wonder if it has anything to do with loading emojis (I am using those for the folder and file icons), will make some experiments soon

**Comment by marc2332** [comment]
after some testing

- not related to emojis
- not related to https://github.com/marc2332/valin/issues/52#issuecomment-2144031556

mmm

**Comment by marc2332** [comment]
> For whatever reason when I open a folder in freya-editor, all SVGs stop working

Actually, it also happens in other situations, I don't see any pattern

**Comment by pragmatrix** [comment]
If you are confident that the problem is in the Skia part, I suggest to compile the project with SKIA_DEBUG=1. May be some assertions will show up in the terminal output when the SVGs fail to render.

**Comment by marc2332** [comment]
> If you are confident that the problem is in the Skia part, I suggest to compile the project with SKIA_DEBUG=1. May be some assertions will show up in the terminal output when the SVGs fail to render.

I tried to compile it on the CI but I couldn't get it to work

And now I tried to compile it on my linux but got `SIGSEGV: child process 'cargo' core dumped`  when finally running the binary, any other way I could do it?

**Comment by marc2332** [comment]
Any idea why is it crashing with `SKIA_DEBUG = 1`? @pragmatrix

**Comment by pragmatrix** [comment]
No, but the next step would be to take a closer look with a debugger or analyze the crash dump.

**Comment by marc2332** [comment]
Closed by https://github.com/marc2332/valin/commit/69e621abeb53c761792a0f77bc35dc03874b2fbd
